# Python Assignment: Data Structures,Functions, Numpy & Pandas

### Section A: Data Structures & Control Structures

In [1]:
my_list=[2,4,5,9,1]


In [2]:
## append
my_list.append(8)
my_list

[2, 4, 5, 9, 1, 8]

In [3]:
## extend
my_list.extend([2,7])
my_list

[2, 4, 5, 9, 1, 8, 2, 7]

In [4]:
## insert
my_list.insert(6,3)
my_list

[2, 4, 5, 9, 1, 8, 3, 2, 7]

In [5]:
## remove
my_list.remove(9)
my_list

[2, 4, 5, 1, 8, 3, 2, 7]

In [6]:
## POP
my_list.pop(2)

5

In [7]:
my_list

[2, 4, 1, 8, 3, 2, 7]

In [8]:
## index
my_list.index(3)

4

In [9]:
##count
my_list.count(2)

2

In [10]:
## sort
my_list.sort()
my_list

[1, 2, 2, 3, 4, 7, 8]

In [11]:
## Reverse
my_list.reverse()
my_list

[8, 7, 4, 3, 2, 2, 1]

In [12]:
## clear
my_list.clear()
my_list

[]

In [13]:
## creeate tuple
student=('Arya','Amrith','Sam')
student

('Arya', 'Amrith', 'Sam')

In [14]:
## try change  
#student[1]='Renu'
# It will raise an error

In [15]:
set_int={1,3,2,4,6,2,9,}
set_int

{1, 2, 3, 4, 6, 9}

In [16]:
my_dict={'Name':['Anu','Manav','Gouri'],'Age':[20,21,22],'City':['Bangalore','Pune','Delhi']}
my_dict


{'Name': ['Anu', 'Manav', 'Gouri'],
 'Age': [20, 21, 22],
 'City': ['Bangalore', 'Pune', 'Delhi']}

In [17]:
my_dict['Age'][0]=23
my_dict['Email']=['anu@gmail.com','manav34@yahoo.com','gouri22@gmail.com']
my_dict

{'Name': ['Anu', 'Manav', 'Gouri'],
 'Age': [23, 21, 22],
 'City': ['Bangalore', 'Pune', 'Delhi'],
 'Email': ['anu@gmail.com', 'manav34@yahoo.com', 'gouri22@gmail.com']}

In [18]:
age=int(input('Enter Age:'))
if age>=18:
    print('You are',age,'years old and eligible to vote ')
else:
    print('Sorry, you are',age,'years old and not eligible to vote')

Enter Age: 22


You are 22 years old and eligible to vote 


In [19]:
marks=[88,92,41,63,76,56]
for i in marks:
    if i>=90:
        grade='A'
    elif i>=75:
        grade='B'
    elif i>=50:
        grade='C'
    else:
        grade='FAIL'
    print('Marks:',i,' Grade:',grade)

Marks: 88  Grade: B
Marks: 92  Grade: A
Marks: 41  Grade: FAIL
Marks: 63  Grade: C
Marks: 76  Grade: B
Marks: 56  Grade: C


In [20]:
Num=int(input('Enter a number:'))
if Num>0:
    if Num%2==0:
        print(Num,'is positive and it is even')
    else:
        print(Num,'is positive and it is odd')
elif Num==0:
    print('Number is Zero')
else:
    print(Num,'is a negative number')


Enter a number: 9


9 is positive and it is odd


### Section B: Numpy

In [21]:
import numpy as np

In [22]:
## Scalar
scalar=np.array(5)
scalar

array(5)

In [23]:
scalar.ndim

0

In [24]:
# 1D
One_dim=np.arange(1,6)
One_dim

array([1, 2, 3, 4, 5])

In [25]:
One_dim.ndim

1

In [26]:
## 2D
Two_dim=np.arange(10,61,10).reshape(2,3)
Two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [27]:
Two_dim.ndim

2

In [28]:
##np.random.randint(0,100,16).reshape(4,4)
np.random.randint(0,100,size=(4,4))

array([[98, 64, 97,  1],
       [ 8, 29, 25, 17],
       [87, 43, 69, 69],
       [87,  0, 51, 39]], dtype=int32)

In [29]:
Two_D=np.array([[2,4,1],[8,7,6],[5,2,1]])
Two_D

array([[2, 4, 1],
       [8, 7, 6],
       [5, 2, 1]])

In [30]:
import pandas as pd
Df=pd.DataFrame(Two_D,columns=['A','B','C'])
Df

A  B  C
0  2  4  1
1  8  7  6
2  5  2  1

### Section C: Exploring Pandas

In [31]:
Df=pd.DataFrame({
    'Name':['Amal','Abhi','Anu','Shreya','Thanu','Rahul','Martin','Amal','Eza','Zenha'],
    'Age':[20,23,18,19,22,21,23,20,24,20],
    'City':['chennai','Bangalore','Chennai','Pune','Bangalore','Pune','Mumbai','Chennai','Mumbai','Pune'],
    'Salary':[10000,12000,np.nan,20000,12000,np.nan,25000,10000,30000,20000]})
Df

Name  Age       City   Salary
0    Amal   20    chennai  10000.0
1    Abhi   23  Bangalore  12000.0
2     Anu   18    Chennai      NaN
3  Shreya   19       Pune  20000.0
4   Thanu   22  Bangalore  12000.0
5   Rahul   21       Pune      NaN
6  Martin   23     Mumbai  25000.0
7    Amal   20    Chennai  10000.0
8     Eza   24     Mumbai  30000.0
9   Zenha   20       Pune  20000.0

In [32]:
##info
Df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [33]:
##describe
Df.describe()

Age        Salary
count  10.000000      8.000000
mean   21.000000  17375.000000
std     1.943651   7539.183359
min    18.000000  10000.000000
25%    20.000000  11500.000000
50%    20.500000  16000.000000
75%    22.750000  21250.000000
max    24.000000  30000.000000

In [34]:
## Name and city
Df[['Name','City']]

Name       City
0    Amal    chennai
1    Abhi  Bangalore
2     Anu    Chennai
3  Shreya       Pune
4   Thanu  Bangalore
5   Rahul       Pune
6  Martin     Mumbai
7    Amal    Chennai
8     Eza     Mumbai
9   Zenha       Pune

In [35]:
## drop city
Df.drop(columns=['City'],inplace=True)
Df

Name  Age   Salary
0    Amal   20  10000.0
1    Abhi   23  12000.0
2     Anu   18      NaN
3  Shreya   19  20000.0
4   Thanu   22  12000.0
5   Rahul   21      NaN
6  Martin   23  25000.0
7    Amal   20  10000.0
8     Eza   24  30000.0
9   Zenha   20  20000.0

In [36]:
##fill null values  in salary using mean
Df.isnull().sum()

Name      0
Age       0
Salary    2
dtype: int64

In [37]:
Df['Salary']=Df['Salary'].fillna(Df['Salary'].mean())
Df

Name  Age   Salary
0    Amal   20  10000.0
1    Abhi   23  12000.0
2     Anu   18  17375.0
3  Shreya   19  20000.0
4   Thanu   22  12000.0
5   Rahul   21  17375.0
6  Martin   23  25000.0
7    Amal   20  10000.0
8     Eza   24  30000.0
9   Zenha   20  20000.0

In [38]:
##Duplicated values
Df.duplicated().sum()
Df[Df.duplicated()]

Name  Age   Salary
7  Amal   20  10000.0

## Df.drop_duplicates(ignore_index=True,inplace=True)
Df